import type { Metadata } from "next";
import "./globals.css";
import { TopBar } from "@/components/topBar";
import { ThemeProvider } from "next-themes";
import { Roboto } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={roboto.className}>
        {/* Provider locale */}
        <NextIntlClientProvider messages={messages}>
          {/* Provider light & dark theme */}
          <ThemeProvider>
            <TopBar />
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
